version: "2"

services:
  product_inspection:
    image: akawato2018/product-inspection:0.0
    ports:
         - "8000:3000"
    network_mode: bridge
    volumes:
    - datastore:/usr/src/app/db/
volumes:
  datastore:
    driver_opts:
      type: none
      device: /var/lib/customer/ftp-data/
      o: bind
